# Generated by Django 4.1.5 on 2023-01-28 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0006_remove_coments_1_user_coments_1_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coments_1",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
